name: iOS CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Show available schemes
      run: xcodebuild -list -project QuoteHub.xcodeproj

    - name: Clean Build Folder
      run: xcodebuild clean -project QuoteHub.xcodeproj -scheme QuoteHub

    - name: Build
      run: |
        xcodebuild build \
          -project QuoteHub.xcodeproj \
          -scheme QuoteHub \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -project QuoteHub.xcodeproj \
          -scheme QuoteHub \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Generate Code Coverage Report
      if: success()
      run: |
        xcrun xccov view --report --only-targets \
          $(find ~/Library/Developer/Xcode/DerivedData -name '*.xcresult' | head -n 1)/action.xccovreport || true

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ~/Library/Logs/scan/
          ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
        retention-days: 7
